### ISSUE TITLE
[Crash - Startup] net.minecraft.client.audio.SoundHandler

### ISSUE THREAD

**Issue by Foreck1** [ACGaming/UniversalTweaks#1]
First issue woo

Game crashes on heavily modded environment:
`Caused by: java.lang.ClassNotFoundException: net.minecraft.client.audio.SoundHandler`

Log: 
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/9921327/latest.log)
Crash report:
[crash-2022-11-02_11.34.19-client.txt](https://github.com/ACGaming/UniversalTweaks/files/9921330/crash-2022-11-02_11.34.19-client.txt)

MixinBooter version: !mixinbooter-4.2.jar

**Comment by ACGaming** [comment]
Surge‘s functionality is superseded by this mod and should be removed.
Can you try again without it?

**Comment by ACGaming** [comment]
Just noticed that you have quite some sound mods installed, looking into that...

**Comment by ACGaming** [comment]
Additional steps:
Please try to set the config toggle `Disable Audio Debug` to `false`.
If that won‘t help, you can set `Obsolete Mods Screen` to `false`. You will still get a crash when incompatible mods are found.
