### ISSUE TITLE
Login hp rounding issue

### ISSUE THREAD

**Issue by FakeDomi** [ACGaming/UniversalTweaks#107]
Login hp can get rounded down to 0 when you have a lot of max hp and only 1 hp.

https://cdn.discordapp.com/attachments/895732613090779189/1088965817502273567/image.png

On login, it doesn't produce a death message and in combination with Corail Tombstone it wipes your main inventory (haven't tried without Corail, it also doesn't wipe baubles or cosmetic armor).

**Comment by FakeDomi** [comment]
Shouldn't it be 0.01F?
I'd vouch for a completely different system altogether since converting a float with only two decimal places back doesn't give the precise number when over a hundred max hp

**Comment by ACGaming** [comment]
Granted, not too content with the current implementation either.

**Comment by ACGaming** [comment]
Alright, the modern Mixin solution from Max Health Fix has far less bullshit involved. Tests turned out positive.
@FakeDomi Can you test again with [this build](https://github.com/ACGaming/UniversalTweaks/suites/11805856743/artifacts/616231122) and report back? Danke!

**Comment by FakeDomi** [comment]
Seems good, haven't noticed any weirdness yet.
