### ISSUE TITLE
"Remove Recipe Book" not removing with Cosmetic Armor

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#108]
When i open [Cosmetic Armor](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked) inventory, i could see Recipe Book, even if `Remove Recipe Book` option set to `true`.

![image](https://user-images.githubusercontent.com/936618/227722393-964e3064-9f95-467c-8cae-1dd3a4e9aad1.png)

https://user-images.githubusercontent.com/936618/227722460-874a4856-b753-45af-8a40-66cc2c8c5864.mp4

**Comment by ACGaming** [comment]
Cosmetic Armor has its own implementation of the recipe book button, you‘d have to set `CosArmorDisableRecipeBook` to `true` inside its config.

**Comment by Krutoy242** [comment]
Ok, I found it.

I though that removing recipe button option in UT override it.

**Comment by ACGaming** [comment]
When other mods are handling recipe books on their own and provide an option to disable them, it should be fine.
