### ISSUE TITLE
Crash: NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#12]
I removed `Mixinbooter` mod as incompatible, and now i cant launch modpack.

I don't know the actual reason, but seems like its `Lootr` mod.

```less
[19:15:09] [main/DEBUG] [FML]: Instantiating coremod class LootrCore
[19:15:09] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\mc_client\Instances\E2E-E for Forge Mod Loader
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2860.jar:?]
	[...]
Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_51]
```

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/10134105/debug.log)

Installing `Mixinbooter` back fixes the problem.

**Comment by ACGaming** [comment]
Unable to help with that since MixinBooter is a hard dependency, for Lootr as well. You‘d have to find out which mod is incompatible with MixinBooter in your instance (most likely a mod packing old 0.7 mixins).

**Comment by Krutoy242** [comment]
> You‘d have to find out which mod is incompatible with MixinBooter in your instance

I dont get it. Why i need to find mod that incompatible?  
And what "Incompatible" means? After i installed MixinBooter back, my modpack loaded fine.

Also, could you explain how UniversalTweaks makes MixinBooter incompatible? I always though "incompatible" means "cant run together", but i run them together and its fine.

**Comment by ACGaming** [comment]
Oh, I guess we have a misunderstanding in general here. MixinBooter is _not_ incompatible but a requirement for Universal Tweaks. It‘s used for the majority of bugfixes and tweaks. Not to be confused with other mods that are on the incompatible list. 😉

**Comment by Krutoy242** [comment]
Oh, this is CurseForge issue then.

When i open "incompatible" relations and press page "2" its reset filters to "all relations" so i could see MixinBooter in list near incompatible mods
![image](https://user-images.githubusercontent.com/936618/205441823-8dcf54db-42dc-4010-8565-b4ccb8c45feb.png)
![image](https://user-images.githubusercontent.com/936618/205441877-18ff330d-751c-4d68-af22-bf4fde8cd9ea.png)

**Comment by ACGaming** [comment]
Oh yeah, these filters don‘t work. CurseForge moment!
The [mod file page](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4127829) shows the only reliable list.
