### ISSUE TITLE
Disable Tutorial Toasts tweak sometimes doesn't work

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#123]
![image](https://user-images.githubusercontent.com/8945347/229613084-67f19459-ced4-4ee2-9369-7d63697ff592.png)

Kind of tricky to reproduce, seems to happen on first launch & world on a new Tekkit 2 `1.2.0` survival world. Weird!

**Comment by ACGaming** [comment]
Tekkit 2 gets shipped with the default option `tutorialStep:find_tree` in Default Options‘ options.txt. Setting it to `tutorialStep:none` shall suffice even without the tweak enabled.

**Comment by xJon** [comment]
Thank you! 🕵️‍♂️
