### ISSUE TITLE
Release 1.0.0 Water Damage reduction wildly inconsistent

### ISSUE THREAD

**Issue by Ski-z** [ACGaming/UniversalTweaks#14]
To replicate: 

1. Stand in 2 blocks deep of water. use /tp <player> ~ ~20 ~   (or any +y value)
2. Fall repeatedly
3. Sometimes receive 1 heart of damage, sometimes 8 hearts of damage.

Unless this is intended/vanilla behavior?

EDIT:

It appears this doesn't happen if the player moves a tiny bit on a solid block before "jumping", so it's just some sort of glitch with using /tp that would never occur in survival. My bad!

**Comment by ACGaming** [comment]
Interesting! I‘m depending solely on the vanilla `fallDistance` value, so I guess this gets calculated inconsistently from the game itself when teleporting. But yeah, survival gameplay should be just fine from my playtests.
