### ISSUE TITLE
[Hot take / discussion] Auto Jump Replacement tweak should be removed

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#141]
Increased step height is usually a feature, reserved to high-end gear or special loot in modded content. The fact that players can currently enable it on the client-side feels like client hacks, or just standardizing what is supposed to be a unique feature, for example of IC2C's QuantumSuit. It also poses an unfair disadvantage to players not enabling it in any competitive movement-oriented environment.

**Comment by Turkey9002** [comment]
I actually disable it by default for the same reason as well. I have gear from a few mods that already add increased step height and I didn't want this tweak to overlap. I didn't know the tweak was client-sided, removing it should be fair for servers but I don't think it would stop someone from adding in a mod that does a similar thing to their mods folder?

**Comment by xJon** [comment]
@Turkey9002 Yeah it works client-side even when disabled on server (+ defaults to being enabled). Regarding the last point - players can always add client hacks mods, it's about having such feature integrated into Universal Tweaks which is intended to be a part of every modpack.

**Comment by Turkey9002** [comment]
@xJon
Oof, yeah now I see how big of a problem that is if it's client-side and easily accessible. The tweak could be replaced with something that improves the auto jump mechanic instead, I recently found this [mod](https://www.curseforge.com/minecraft/mc-mods/better-auto-jump) that adds the option to only trigger auto jump when sprinting.
