### ISSUE TITLE
UniversalTweaks issues with TexFix and VanillaFix

### ISSUE THREAD

**Issue by EliteMeats** [ACGaming/UniversalTweaks#151]
When UniversalTweaks is use in the Rebirth of the Night modpack with TF and VF, this error appears upon loading in or creating a world; only once per launch:

https://cdn.discordapp.com/attachments/623268586873421824/1096648325412950159/image.png

Ignoring the message and continuing loads up the world seemingly normally, however there is one issue that I noticed, that being that /bop commands quite literally just don't exist. There are probably more issues that happened that I didn't notice.

However, when UT is used with CensoredASM or NormalASM (which replaces the two Fix mods) there are no issues at all that I can notice; everything runs normally. Alternatively, when TF and VF are loaded without UT it is also normal (albeit without the plethora of fixes UT provides).

After discovering this, I tried loading these mods up in a clean 1.12 vanilla forge instance. ~~When UT is loaded with the Fix mods, it crashes before the game even loads (crash log: https://pastebin.com/exY1PE2X). However with CensoredASM (and its dependency mixinbooter) it loads fine. So, likely there is some issue between codebases of UT and the Fix mods that is causing a strange issue.~~ (mistake, see comments below)

**Comment by jchung01** [comment]
I don't know about the backup level.dat warning, but for the standalone instance's crash it looks like you didn't test with MixinBooter, as UT also requires MixinBooter to function.

**Comment by EliteMeats** [comment]
> I don't know about the backup level.dat warning, but for the standalone instance's crash it looks like you didn't test with MixinBooter, as UT also requires MixinBooter to function.

I'll try that right now

**Comment by EliteMeats** [comment]
Ok, seems I made a little mistake; UT seems to launch fine with TF and VF on the clean instance. My bad lol

**Comment by ACGaming** [comment]
> UT seems to launch fine with TF and VF on the clean instance
Which indicates it‘s some other mod incompatibility within the Rebirth of the Night modpack. I can only really help when you can pinpoint the mod constellation required to reproduce.
