### ISSUE TITLE
Disabling a feature should stop incompatibility screen/crash from appearing.

### ISSUE THREAD

**Issue by fullskele** [ACGaming/UniversalTweaks#16]
Hello, I recently tried this mod out, and didn't like the damage tilt fix as much as the original Damage Tilt mod (poison damage looked strange). 

I disabled the feature in UniversalTweaks.cfg, but was still faced with a crash due to incompatibility, even with Obsolete Mods Screen disabled as well.

Would it be possible to stop incompatibility checks if either of these options are turned off? Thank you.

**Comment by ACGaming** [comment]
Bypassing incompatibility warnings is an upcoming config toggle and is already available in the [early access versions](https://github.com/ACGaming/UniversalTweaks/suites/9730038099/artifacts/466781099).

**Comment by xJon** [comment]
I think that the suggestion is for disabled features to respectively not toggle an incompatibility crash/warning for the conflicting mod.

Regardless of whether that is the original suggestion or not, I also thought of suggesting that, but it is a "premium" UX feature and if it's technically complex to implement - a simple off toggle "you're on your own" feature (which is what's already developed) works fine.

**Comment by ACGaming** [comment]
Granted, going to make the incompatibility toggles more dynamic, for one-off mods at least.

**Comment by ACGaming** [comment]
Concerning the damage tilt tweak in general: I was implementing the client-sided version because it requires less code but I wasn‘t much of a fan of the visuals myself either, so I implemented the server-sided version in https://github.com/ACGaming/UniversalTweaks/commit/daf25a8f08c83e9ba2fb50cb24ba547364175ce0.
