### ISSUE TITLE
[Feature Request] Backport TTF/OTF font loading via resource packs

### ISSUE THREAD

**Issue by vico93** [ACGaming/UniversalTweaks#161]
First of all, sorry if this idea is out of the scope of this mod.

Currently i'm using BetterFonts to change the game font by a True/OpenType font, But it requires the font file to be installed on the system, what can be annoying and impractical if the Windows user doesn't have administrator privilegies.

So, backporting the [TTF/OTF font declaration from post-1.13](https://minecraft.fandom.com/wiki/Resource_pack#Fonts) would greatly facilitate things and keep that more similarly to how vanilla works.

**Comment by ACGaming** [comment]
Unsure if that‘s inside the scope of Universal Tweaks but I leave it open for the time being.
In the meantime, you could utilize [Smooth Font](https://legacy.curseforge.com/minecraft/mc-mods/smooth-font) and provide the respective font in the `fontfiles` folder. No font installation required!

**Comment by vico93** [comment]
Well, i will keep using BetterFonts for the time being
