### ISSUE TITLE
[Feature Request] Legacy Fabric port

### ISSUE THREAD

**Issue by vico93** [ACGaming/UniversalTweaks#169]
Well, i don't know if you have interest in doing this, but i think players on [Legacy Fabric](https://legacyfabric.net/) 1.12.2 would benefit a lot of your mod on that modloader.

[LF's discord if you want to have more information](https://legacyfabric.net/discord).

**Comment by MiFliK** [comment]
are there many mods on legacy fabric lol

if you port it all at once
