### ISSUE TITLE
Breakable Bedrock/Unbreakable blocks?

### ISSUE THREAD

**Issue by Lylythii** [ACGaming/UniversalTweaks#17]
Would be great to allow the breaking of bedrock blocks. Nothing should be eternal. :)

**Comment by ACGaming** [comment]
Noted! Should be rather easy.

**Comment by Turkey9002** [comment]
Going to chime in and mention flat bedrock too because I got reminded. ^^; I also think adding a list for tools that can break bedrock or setting minimum mining level would be great too. I personally am going to set Thaumcraft's Void Pickaxes to break them with that option.
