### ISSUE TITLE
What means `WARN: @Mixin target was not found UTDefaultDifficultyMPMixin`?

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#180]
After one of recently UT updates, i found new WARN line in my `debug.log` file:

```less
[main/WARN] [mixin]: @Mixin target net.minecraft.server.dedicated.DedicatedServer was not found mixins.tweaks.misc.difficulty.json:UTDefaultDifficultyMPMixin
```

There is few other errors related to this one:

```less
RuntimeException: Attempted to load class nz for invalid side CLIENT
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
```
```less
Error loading class: net/minecraft/server/dedicated/DedicatedServer (net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@781bd9dd from coremod FMLCorePlugin)
```

What this warnings means? Does this means `S:"Default Difficulty"=NORMAL` option not working at all?

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/11451739/debug.log)

**Comment by ACGaming** [comment]
The tweak consists of two parts: One for the integrated server (singleplayer) and one for the dedicated server (multiplayer). One of them fails to apply, depending on the situation.
The tweak itself works just fine, I can separate the parts properly for the next release though.
