### ISSUE TITLE
[Bug]UniversalTweaks v1.6.0 conflicts with the TouhouLittleMaid mod

### ISSUE THREAD

**Issue by 200542053** [ACGaming/UniversalTweaks#183]
UniversalTweaks v1.6.0 conflicts with the [TouhouLittleMaid](https://legacy.curseforge.com/minecraft/mc-mods/touhou-little-maid) mod, causing the game to crash upon joing the world. It appears to be related to LinkedHashSet. 
Changing the S:"Tile Entity Map" from "CONCURRENT_LINKED_HASHMAP" to "HASHMAP" does not resolve the issue, the game continues to crash with the same error message. 
Reverting back to version 1.5.0 eliminates this problem.
[crash-2023-05-13_10.47.24-server.txt](https://github.com/ACGaming/UniversalTweaks/files/11468743/crash-2023-05-13_10.47.24-server.txt)

**Comment by ACGaming** [comment]
This is unrelated to tile entities, you have enabled the `Concurrent Entity AI Tasks` bugfix which is not compatible in every modded scenario, hence disabled by default. Setting it back to `false` helps your case, just reproduced it.
