### ISSUE TITLE
Crafting Cache dupes w/ IC2 Classic's stacked recipes

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#189]
(Reported over https://github.com/xJon/Tekkit-2/issues/190)
> When crafting the Rotary Macerator, pressumably with resources for 2 of more, it allows for the infinite crafting of Rotary Macerators.
It happens when using the recipe with the Obsidian blades requiring 2 per slots in the crafting table.
>
> Upon clicking an item in the crafting grid after crafting the item, the items return as if the item was not crafting, except you get to keep it.
>
> I have added a video of the "dupe" in action.
> 
> https://github.com/xJon/Tekkit-2/assets/72791212/8955b72b-3e3b-483f-8cf1-333d796478df

I managed to reproduce this on a server. Disabling the crafting cache "fixes" the issue.
On a singleplayer the game crashes instead: https://mclo.gs/tl0VSCc, in a server it prints a similar error to log but doesn't crash.

**Comment by ACGaming** [comment]
Do note that Tekkit 2 doesn‘t include the fix yet. 😉

**Comment by DjordjeMandic** [comment]
May be useful info for someone, here is hei_bookmarks.ini content containing affected items

```
T:{id:"ic2:blockmachinemv",Count:1b,Damage:2s}
T:{id:"ic2:blockelectric",Count:1b,Damage:1s}
T:{id:"ic2:blockelectric",Count:1b,Damage:9s}
T:{id:"ic2:blockmachinelv2",Count:1b,Damage:6s}
T:{id:"ic2:itemmisc",Count:1b,Damage:264s}
T:{id:"ic2:iteminactivefuelcell",Count:1b,Damage:2499s}
T:{id:"ic2:itemmisc",Count:1b,Damage:160s}
T:{id:"ic2:itemdrills",Count:1b,tag:{ench:[{lvl:3s,id:35s}]},Damage:1s}
T:{id:"ic2:itemportableteleporter",Count:1b,Damage:0s}
T:{id:"ic2:itemmetascanners",Count:1b,Damage:1s}
T:{id:"ic2:itemmetascanners",Count:1b,Damage:2s}
T:{id:"ic2:itemmetascanners",Count:1b,Damage:3s}
T:{id:"ic2:itemmetascanners",Count:1b,Damage:10s}
T:{id:"ic2:itemmachinetool",Count:1b,Damage:0s}
T:{id:"ic2:ic2upgrades",Count:1b,Damage:0s}
T:{id:"minecraft:elytra",Count:1b,Damage:0s}
T:{id:"ic2:itemheatstorage",Count:1b,Damage:1s}
T:{id:"gravisuit:advanceddrill",Count:1b,Damage:0s}
T:{id:"gravisuit:advancedchainsaw",Count:1b,tag:{},Damage:0s}
T:{id:"ic2:itemquantumarmornuclearjetplate",Count:1b,Damage:0s}
T:{id:"ic2:itemquantumarmorjetpack",Count:1b,Damage:0s}
T:{id:"ic2:itemarmornuclearcombindedjetpack",Count:1b,Damage:0s}
T:{id:"ic2:itemarmorcombinedjetpack",Count:1b,Damage:0s}
```
