### ISSUE TITLE
[bugs]classicbar and SimpleDifficulty Incompatible

### ISSUE THREAD

**Issue by Lonelyxiya** [ACGaming/UniversalTweaks#190]
#https://github.com/juraj-hrivnak/SimpleDifficulty/issues/2
Do you have a way to fix these up? Because I had to leave the classicbar mod

**Comment by ACGaming** [comment]
Well, that‘s not a bug, there‘s simply no integration for SimpleDifficulty within Classic Bars. Best fit for an own fork, not really inside the scope of Universal Tweaks.
