### ISSUE TITLE
Crafting Cache ArrayOutOfBoundsException: -1

### ISSUE THREAD

**Issue by marilatte53** [ACGaming/UniversalTweaks#195]
I was using my Applied Energistics 2 Crafting Terminal when suddenly I couldn't open it anymore, everytime I tried it would cause the following Exception:
[universal_tweaks_crash.txt](https://github.com/ACGaming/UniversalTweaks/files/11577499/universal_tweaks_crash.txt)
I tried restarting the _world_ (**Single Player!**) multiple times and came to the conclusion that the Crafting Cache was the issue. After restarting the _game_, it was working again.

**Comment by ACGaming** [comment]
Thanks for reporting, got some questions concerning this:
- So did you keep the tweak enabled and it works again after a game restart?
- Can you remember the last thing you have crafted before it started crashing?
- Which modpack are you playing?

**Comment by marilatte53** [comment]
sorry for not replying...

- Yes, I didn't change anything about the mods or config, it seemed to be a one-time problem 
- I do not remember the last thing I crafted, but I _believe_ the crash was caused by inserting items into the crafting grid using JEI 
- The modpack was Divine Journey 2 (There is a Discord server and I believe that other people have had this issue too, so maybe that might help)

**Comment by ACGaming** [comment]
Thanks for the insight, let me know if this should happen again!
