### ISSUE TITLE
Some mods don't work properly with MixinBooter 8 installed

### ISSUE THREAD

**Issue by HaHaWTH** [ACGaming/UniversalTweaks#205]
I updated my MixinBooter to 8.2, lots of mixins of other mods do not work properly such as VanillaFix
[LoliKingdom/MixinBooter#31](https://github.com/LoliKingdom/MixinBooter/issues/31)

**Comment by ACGaming** [comment]
Proper support for MixinBooter 8 is implemented in 7190ec0dcc02f85f633d7007d55ca50d58933bde and will be part of the 1.7.0 update.

**Comment by HaHaWTH** [comment]
Emmm...I mean i could only use MixinBooter 7.1 for some mods like RLmixins and VanillaFix, but the latest version of UniversalTweaks does not support MixinBooter 7.1 :( it will crash

**Comment by ACGaming** [comment]
This is within MixinBooter‘s area of responsibility. Follow the progress [here](https://github.com/LoliKingdom/MixinBooter/issues/34).
