### ISSUE TITLE
[Suggestions]: Item models fix

### ISSUE THREAD

**Issue by magcicada** [ACGaming/UniversalTweaks#21]
There are two mods fixed [MC-73186](https://bugs.mojang.com/browse/MC-73186) in 1.16 and above version: [Item Stitching Fix](https://www.curseforge.com/minecraft/mc-mods/item-stitching-fix) and [Item Model Fix (Fabric)](https://www.curseforge.com/minecraft/mc-mods/item-model-fix).
They fixed those transparent lines in all generated item models, but no mod as the same action in MC 1.12.2, can you have a look?

**Comment by Turkey9002** [comment]
[Model Gap Fix](https://www.curseforge.com/minecraft/mc-mods/model-gap-fix) is also worth checking out. It fixes that bug too except it also expands the fix to block models and anything else with similar functions.

**Comment by ACGaming** [comment]
I was indeed looking at Model Gap Fix for the most benefit and already have a rough idea how to port it.

**Comment by ACGaming** [comment]
Implemented in b9db7386d880aba0e196a28ff22fe85d0944d099.
