### ISSUE TITLE
Fast World Loading introduce TPS lag during worldgen when enabled

### ISSUE THREAD

**Issue by quentin452** [ACGaming/UniversalTweaks#215]
Fast World Loading introduce TPS lag during worldgen when enabled
tps profiled using Patcher mod

**mods lists**

Essential-Forge-1.12.2
!mixinbooter-8.3
Patcher-1.8.7 (1.12.2)
spark-forge1122
UniversalTweaks-1.12.2-1.6.0

**spark profiler**

-Fast World Loading enabled

https://spark.lucko.me/DR8IQVEklN

-Fast World Loading disabled

https://spark.lucko.me/QzXHgW7gcw

**videos**

-Fast World Loading enabled(151ms max)

https://mega.nz/file/78dzFAiA#pFsHd5xYotSb2assSN6Pq_Z4QbKC05Lu_wYMGpuKykQ

-Fast World Loading disabled(80ms max)

https://mega.nz/file/SlVxVLpJ#Q4txVu9UPWqV11RxpREOyNdEtWOj6gdZlEx6VfWH8Yg

**Comment by ACGaming** [comment]
Side effects of these tweaks were reported, adjusted the config in https://github.com/ACGaming/UniversalTweaks/commit/073c550a8b050d339ada863f4c6b9d518b40e617 accordingly.
