### ISSUE TITLE
Game lags then crashes after killing an enemy

### ISSUE THREAD

**Issue by vizthex123** [ACGaming/UniversalTweaks#217]
Hope this gets fixed soon. Love the concept of this mod.

Log:
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/11877045/latest.log)

**Comment by vizthex123** [comment]
Also seems to have corrupted my world, as I can no longer load it even after disabling the mod.

Loaded a backup and it worked fine.

Log:
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/11877122/latest.log)

**Comment by ACGaming** [comment]
What makes you believe it‘s related to Universal Tweaks? Couldn‘t notice anything at first glance.
Also, you can get rid of Surge since its functionality is included.

**Comment by vizthex123** [comment]
Cuz I hadn't used it before and it worked when I disabled it.

Still can't figure it out, but I am sorry for the false report.

**Comment by ACGaming** [comment]
So this issue won‘t occur when Universal Tweaks is disabled or removed? Then it would be a valid report, just with an unknown origin.

**Comment by vizthex123** [comment]
Finally found out it was Dupe Fix Project of all things.

Works fine with this installed, so yeah it wasn't Universal Tweaks' fault.

**Comment by ACGaming** [comment]
Interesting, thank you for figuring out! Good to know the source for future reference.
