### ISSUE TITLE
[Suggestion] Add in functionality from BurnBabyBurn, FastFurnace, and Reach Fix

### ISSUE THREAD

**Issue by vizthex123** [ACGaming/UniversalTweaks#218]
[BurnBabyBurn](https://www.curseforge.com/minecraft/mc-mods/burnbabyburn) makes baby zombies burn during the daytime (like in new MC versions), [FastFurnace](https://www.curseforge.com/minecraft/mc-mods/fastfurnace) is just FastWorkbench for the furnace, and [Reach Fix](https://www.curseforge.com/minecraft/mc-mods/reach-fix) fixes problems with the reach attribute.

Also noticed that it doesn't detect [Old Combat Mechanics](https://www.curseforge.com/minecraft/mc-mods/old-combat) upon loading.

**Comment by ACGaming** [comment]
FastFurnace functionality is included in [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) which is widely used in modpacks and [Reach Fix](https://www.curseforge.com/minecraft/mc-mods/reach-fix) is still actively maintained and thus won‘t be included for now.
