### ISSUE TITLE
"Fast World Loading" Does the opposite when using performance mods.

### ISSUE THREAD

**Issue by toErIpNid** [ACGaming/UniversalTweaks#221]
Universal Tweaks when installed creates significant world gen slowdown despite it's feature advertising otherwise. This is remedied by disabling fast world gen surprisingly enough and everything is back to being fast as hell afterwards. 

Log **before** disabling Fast Gen: https://hastebin.skyra.pw/iqemevufos.md

Log **after** disabling Fast Gen: https://hastebin.skyra.pw/dikenutobo.md

Not sure if this is a bug or intended feature, but letting you guys know anyways in case it's not intended.

**Comment by ACGaming** [comment]
Fast World Loading just speeds up loading worlds from the main menu and possibly has other side effects as this. Going to change the default value and apply a warning accordingly.
