### ISSUE TITLE
[bug]The windows cannot pop up.

### ISSUE THREAD

**Issue by Lonelyxiya** [ACGaming/UniversalTweaks#222]
After upgrading from UT 1.6.0 to 1.7.0, the pop-up windows are not functioning properly.
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/11979780/latest.log)

**Comment by ACGaming** [comment]
Missing [ConfigAnytime](https://www.curseforge.com/minecraft/mc-mods/configanytime)
