### ISSUE TITLE
Can you revert mixin booter 8.0 required to 7.1 because mixinboot 8.0+ have some issues with mods

### ISSUE THREAD

**Issue by quentin452** [ACGaming/UniversalTweaks#225]
https://github.com/LoliKingdom/MixinBooter/issues/38
https://github.com/focamacho/DupeFix-Project/issues/106
https://github.com/LoliKingdom/MixinBooter/issues/34

**Comment by ACGaming** [comment]
Resolved as there is [this branch](https://github.com/ACGaming/UniversalTweaks/tree/mb7) along with [this release](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4630071).
