### ISSUE TITLE
[Bug] Draconic armor flight speed modifier has no effect with UniversalTweaks v1.7.0

### ISSUE THREAD

**Issue by AlexanderLaptev** [ACGaming/UniversalTweaks#233]
## Description
The Flight Speed Modifier from Draconic Evolution's Draconic Chestplate has no effect on the speed of flight when using UniversalTweaks v1.7.0. The issue still persists after disabling all available tweaks and bugfixes in the config. The bug does not happen with UniversalTweaks v1.6.0 and v1.4.0.
## Versions
Java: 1.8.0_51 64-bit
Minecraft: 1.12.2
Forge: 14.23.5.2859 and 2860
Universal Tweaks: 1.12.2–1.7.0
Draconic Evolution: 1.12.2–2.3.28.354

MixinBooter: 8.3
ConfigAnytime: 1.0
Brandon's Core: 2.4.20.162
CodeChicken Lib: 3.2.3.358

**Comment by ACGaming** [comment]
Pretty certain this is fixed with the mentioned commit. If not, feel free to re-open!
