### ISSUE TITLE
Regarding commit 13309a9 (Sea level)

### ISSUE THREAD

**Issue by Primitive-Human** [ACGaming/UniversalTweaks#236]
I see you've recently added this to change the default sea level that is generated. 

Considering that UT is only developed for MC 1.12.2 that still has the Custom World generator, where you can adjust the sea level in the generator profile, I wonder if this new tweak overrides the sea level that has been setin the custom world generator profile. 

For example, I set it in UT to Y = 150, will it automatically change the default in the custom world generator to Y = 150? Or will it override anything I set in there, like Y = 200 gets ignored?

**Comment by ACGaming** [comment]
The tweak only sets the default values for chunk generation, so you could technically still change it to your liking in the custom world settings.

You‘d be best advised to either use the tweak **or** the built-in custom world generator though, as the tweak was primarily designed to be utilized with mods that introduce their own generation. If the config is left at the value `63`, the tweak is disabled inherently and won‘t interfere with anything.
