### ISSUE TITLE
[Question] Where is the experience bug fix functionnality

### ISSUE THREAD

**Issue by quentin452** [ACGaming/UniversalTweaks#245]
I searched arround the config and can't find

**Comment by ACGaming** [comment]
What tweak are you looking for? Please describe the functionality.

**Comment by quentin452** [comment]
this https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug : the bugfix should be in the mod , but can't find it

**Comment by quentin452** [comment]
i think there is a mistake that make the bugfix not loaded?

**Comment by ACGaming** [comment]
This is part of the `Dimension Change Player States` bugfix which includes more player statistics than just experience.

**Comment by quentin452** [comment]
ok thx
