### ISSUE TITLE
Setting to disable flight speed config

### ISSUE THREAD

**Issue by evilchin** [ACGaming/UniversalTweaks#247]
From my testing it seems that the config option "D:"[3] Fly Speed" is affecting variable flight speeds for some mods' items. The main example for me is that it makes the flight speed static no matter if you use the ring of dragons or ring of fairies from [Trinkets and Baubles]. Setting the config option "B:"[1] Player Speed Toggle" to false does not fix this problem in testing, as I'm guessing that option only affects walk and run speed. 

The root cause may be related to #233 .

**Versions**
-----------------------------
Minecraft: 1.12.2
Forge: 14.23.5. 2860
Universal Tweaks: 1.12.2–1.7.1
Trinkets and Baubles: 1.12.2–32.4
MixinBooter: 8.3
ConfigAnytime: 1.0

**Comment by ACGaming** [comment]
Key question is: Does it still make flight speed ‚static‘ if the master switch `Player Speed Toggle` is set to false and the game was restarted?

**Comment by evilchin** [comment]
Yea that’s the issue for me. The master switch in the config isn’t disabling flight speed changes when the mod is installed. So no matter what, your flight speed is static when playing and instance with universal tweaks loaded.

**Comment by ACGaming** [comment]
Alright, then this is indeed a bug.
