### ISSUE TITLE
an experience

### ISSUE THREAD

**Issue by Xikaro** [ACGaming/UniversalTweaks#25]
When you die, the experience you have is doubled.

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/10326326/debug.log)
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/10326327/latest.log)
![Screenshot_75](https://user-images.githubusercontent.com/55663835/210113050-2185e1e9-99dc-412f-85e6-fd9aafe63275.png)
![Screenshot_76](https://user-images.githubusercontent.com/55663835/210113082-d7c9bbdd-a1e4-4709-9dc1-2c8ea904fd46.png)
![Screenshot_77](https://user-images.githubusercontent.com/55663835/210113084-ced20ec5-40f9-466e-b50b-53a6d339b997.png)

**Comment by Xikaro** [comment]
config is generated by default

**Comment by ACGaming** [comment]
Great observation!
