### ISSUE TITLE
Corail tombsone particle effect/fog make liquid invisible caused by Depth Mask

### ISSUE THREAD

**Issue by quentin452** [ACGaming/UniversalTweaks#252]
Screenshot : 
Depth Mask on :
![image](https://github.com/ACGaming/UniversalTweaks/assets/42176772/ec972e3c-6fb0-4c8b-b1b1-095be2a6eaec)

Steps : 

0 : enable Depth Mask into Universal Tweaks
1 : add an item in your inventory
2 : make a /kill
3 : go to the tombstone location 
4 : watch liquid become invisible when Depth mask is activated

Mods list : 

!configanytime-1.0
!mixinbooter-8.3
tombstone-4.6.2-1.12.2
UniversalTweaks-1.12.2-1.7.1

**Comment by ACGaming** [comment]
Same as #453, the depth mask bugfix fixes vanilla issues but causes other issues with mods which already built around the flawed vanilla behavior.
