### ISSUE TITLE
Erroneously errors when using MixinCompat that loads both 0.8 and 0.7

### ISSUE THREAD

**Issue by Xetaxheb** [ACGaming/UniversalTweaks#255]
https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility
Allows you to run 0.8 with 0.7 and its mods but UT mistakenly thinks only 0.7 is loaded

**Comment by ACGaming** [comment]
What mods are you using that still have Mixin v0.7 bundled? Do note that this is unrelated to the MixinBooter 7/8 dependency.

**Comment by Desoroxxx** [comment]
MixinBooter 7/8 != Mixin 0.7-0.8

**Comment by ACGaming** [comment]
Wouldn‘t even know where to start here, MixinBooter versions were never made to be used concurrently and, although seemingly not hard-crashing, I can imagine quite a few Mixin-related issues under the hood.
Cleanest way would be to use the designated MixinBooter 7-compatible version of Universal Tweaks or move on to MixinBooter 8 altogether if possible.
