### ISSUE TITLE
Crash with Phosphor, MaLiLib and RenderLib

### ISSUE THREAD

**Issue by X-XLebyshek** [ACGaming/UniversalTweaks#258]
Minecraft 1.12.2
Forge 14.23.5.2860 (the latest)
Universal Tweaks 1.7.1 (the latest)
Phosphor 0.2.7 (the latest)
MaLiLib 0.10.0-dev.23
RenderLib 1.3.2 (the latest)

When I launch Minecraft, it comes to the 1 phase and then crashes. I get such a crash-report:

https://justpaste.it/1u8fb

The crash-report was too long, so I couldn't fit it here.

**Comment by ACGaming** [comment]
Most likely not connected to Universal Tweaks, this might be the Phosphor issue with MixinBooter 8. Please utilize [Hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus) instead.

**Comment by X-XLebyshek** [comment]
It diddn't help.

**Comment by X-XLebyshek** [comment]
I also tried without phosphor and it crashed anyways

**Comment by X-XLebyshek** [comment]
Oh, I found a problem mod. It was Integrated Proxy, it was written about this mod at the very beginning of the crash report.

**Comment by ACGaming** [comment]
Oh, that‘s actually an own mod, thought it was part of a mod which included Mixin itself. Glad this is settled!
