### ISSUE TITLE
UT-1.8.0-MB7 requires Mixin Booter 8

### ISSUE THREAD

**Issue by evilchin** [ACGaming/UniversalTweaks#260]
Every time I try to load the latest version, that is meant to work with mixin booter 7.1 instead of 8, I can't get past the start screen. Start screen says it requires mixin booter 8 to load, but this version is supposed to be for 7.1. Can send screenshots and logs if needed.

 **Versions**
------
Minecraft: 1.12.2
Forge: 14.23.5.2860
Universal Tweaks: 1.12.2–1.8.0-MB7
MixinBooter: 7.1
ConfigAnytime: 1.0

**Comment by HaHaWTH** [comment]
I encountered the same issue, due to some problem I could only use MixinBooter 7, but UT requires 8.0+.

**Comment by HaHaWTH** [comment]
Maybe you can try this, It works fine on MixinBooter 7.1
[UniversalTweaks-1.8.0-MB7-bytecoded.zip](https://github.com/ACGaming/UniversalTweaks/files/12344060/UniversalTweaks-1.8.0-MB7-bytecoded.zip)

**Comment by ACGaming** [comment]
Thanks for the report, this was just a quick oversight from my side. Re-uploaded on both CurseForge and Modrinth.
