### ISSUE TITLE
Incompatibility with Immersive Vehicles mod when Entity Desync fix is active

### ISSUE THREAD

**Issue by XvaleX10** [ACGaming/UniversalTweaks#262]
The vehicles disappear after a while as I accelerate
Unfortunately I don't know how to make a clip to show you

**Comment by Castanea43** [comment]
I have the same problem with train from ImmersiveRailroading (ImmersiveRailroading-1.12.2-forge-1.9.1 and the latest test-build on discord : ImmersiveRailroading-1.12.2-forge-1.9.1-e49acbb)
i have to disable : B:"Entity Desync"=true

With, true you can see this video : 
https://www.youtube.com/watch?v=L96BQCsIsBk

**Comment by jchung01** [comment]
I can replicate both issues with Immersive Vehicles and Immersive Railroading.
For either mod, assemble the vehicle and drive it far enough away (~170 blocks) from its original position. The vehicle will glitch out client-side, going invisible with the player technically still on it. It seems to be an issue with these entities not updating their prevPosX/Y/Z. This can be verified with Immersive Railroading by looping the track back towards its start position as in Castanea's video as eventually the train returns to normal when close enough to its start position.
I have provided a fix and tested on both mods that it works.
