### ISSUE TITLE
Crash with Unloader tweak

### ISSUE THREAD

**Issue by XvaleX10** [ACGaming/UniversalTweaks#267]
[crash-2023-08-23_14.45.21-server.txt](https://github.com/ACGaming/UniversalTweaks/files/12419274/crash-2023-08-23_14.45.21-server.txt)
[crash-2023-08-23_14.45.23-client.txt](https://github.com/ACGaming/UniversalTweaks/files/12419275/crash-2023-08-23_14.45.23-client.txt)

**Comment by XvaleX10** [comment]
> What are your config settings for the Unloader tweak? When does the issue occur?

[UniversalTweaks.txt](https://github.com/ACGaming/UniversalTweaks/files/12428455/UniversalTweaks.txt)
I don't know how to reproduce the crash but it happened suddenly while I was exploring a world

**Comment by ACGaming** [comment]
Did you leave any dimension prior to crashing? Let me know if this is reproducable in any form.

**Comment by XvaleX10** [comment]
> Did you leave any dimension prior to crashing? Let me know if this is reproducable in any form.

Yes I had just left the Atum 2 dimension, but as I said I don't know how to reproduce it

**Comment by ACGaming** [comment]
That‘s a good hint though, going to mess around with Atum whenever I get the time.

**Comment by XvaleX10** [comment]
I had this problem again, but this time I didn't enter any dimensions, I was just exploring the overworld
[crash-2023-09-08_12.22.23-server.txt](https://github.com/ACGaming/UniversalTweaks/files/12558419/crash-2023-09-08_12.22.23-server.txt)
[crash-2023-09-08_12.22.25-client.txt](https://github.com/ACGaming/UniversalTweaks/files/12558421/crash-2023-09-08_12.22.25-client.txt)

**Comment by ACGaming** [comment]
Noted, feel free to disable the tweak for the time being.
