### ISSUE TITLE
Game crash when Armor Curve toggle is false and entities attack eachother

### ISSUE THREAD

**Issue by Fuyukai** [ACGaming/UniversalTweaks#271]
If the ``[1] Armor Curve Toggle`` option in the config is false (the default value), then the game will crash when an entity attacks another entity.

The full backtrace: https://gist.github.com/Fuyukai/519495a6f516e3403c1ba7b8bb1fbcfa

The root cause is that it attempts to access ``UTArmorCurve.armor#with`` unconditionally in the ``UTDamageCalculatorMixin`` mixin, but ``UTArmorCurve.armor`` doesn't get set to a value unless that option is set to true.

It also prevents you from attacking any entity with the same error (but the game traps it in the networking code so it doesn't crash).

Using the latest HEAD build.

**Comment by ACGaming** [comment]
Can‘t reproduce. When the master toggle is off, no mixin is loaded and not even the expressions are calculated. 🤔

**Comment by Fuyukai** [comment]
This is actually in a dev environment... which means that all mixins are loaded unconditionally. Oops! That's my bad, I didn't realise it at the time. 

(Or I guess I'll blame intellij text search for not showing me the condition...)

**Comment by ACGaming** [comment]
Good to know, glad it‘s settled!
