### ISSUE TITLE
`UTBannerBoundingBoxMixin` mixin conflict with mod `RenderLib` (`Entity Culling` lib)

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#275]
Launching UT with EntityCulling output this WARN in `debug.log`:

```less
[Client thread/WARN] [mixin]: Method overwrite conflict for getRenderBoundingBox in mixins.bugfixes.blocks.banner.json:UTBannerBoundingBoxMixin from mod UniversalTweaks_1_12_2_1_8_0, previously written by meldexun.renderlib.mixin.MixinTileEntityBanner. Skipping method.
```

Does this means that UT tweaks not working? Is it possible for me to somehow configure both mods to work together?

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/12496244/debug.log)

**Comment by ACGaming** [comment]
Seems like RenderLib is applying the same fix, you can safely disable the bugfix within Universal Tweaks.
Going to handle this automatically for the next update.

**Comment by Krutoy242** [comment]
> Going to handle this automatically for the next update.

Yeah, this would be great. Since in my modpack `E2E-E` RenderLib is optional mod, and not everyone would have its mixins.
