### ISSUE TITLE
"Burning Baby Zombies"

### ISSUE THREAD

**Issue by FanRenLa** [ACGaming/UniversalTweaks#277]
# Lets baby zombies burn in daylight as in Minecraft 1.13+
        B:"Burning Baby Zombies"=true

Zombies don't burn during the day.
![image](https://github.com/ACGaming/UniversalTweaks/assets/83486178/d8490ccc-b332-4409-ab59-5c4426b179a8)

**Comment by Sereath** [comment]
Oh yeah, just now I was about to report this. Thanks.
