### ISSUE TITLE
can not enter aether 

### ISSUE THREAD

**Issue by ralseilii** [ACGaming/UniversalTweaks#282]
i cannot build aether portal from aether as placing water bucket breaks it. i installed universaltweaks 1.8.0 with censormed5.14

**Comment by ACGaming** [comment]
Which version of Aether are you using and which features from Universal Tweaks did you enable?

**Comment by ralseilii** [comment]
just all of newest version and default config

**Comment by ralseilii** [comment]
and i had optifine

**Comment by ACGaming** [comment]
Assuming you have [this version of Aether](https://www.curseforge.com/minecraft/mc-mods/aether) installed, this works just fine for me.
