### ISSUE TITLE
i cant figure out why it keeps crashing please help

### ISSUE THREAD

**Issue by FinnagianNightshad** [ACGaming/UniversalTweaks#288]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.8.0_Forge_1.12.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  MixinBooter (!mixinbooter-8.6.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  UniversalTweaksCore (UniversalTweaks-1.12.2-1.8.0.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  ConfigAnytimePlugin (!configanytime-1.0.jar)
  Better Biome Blend (betterbiomeblend-1.12.2-1.1.7-forge.jar)
  BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 10/13/23 4:03 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

(MixinBooter) Mixins in Stacktrace:
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperClient (mixins.tweaks.misc.buttons.snooper.client.json) [unknown-location]
		mod.acgaming.universaltweaks.tweaks.performance.fps.mixin.UTUncapFPSMixin (mixins.tweaks.performance.fps.json) [unknown-location]
		me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json) [unknown-location]
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperClient (mixins.tweaks.misc.buttons.snooper.client.json) [unknown-location]
		mod.acgaming.universaltweaks.tweaks.performance.fps.mixin.UTUncapFPSMixin (mixins.tweaks.performance.fps.json) [unknown-location]
		me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json) [unknown-location]
	net/minecraftforge/fml/common/LoadController:
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown-location]
	net/minecraft/client/Minecraft:
		mod.acgaming.universaltweaks.tweaks.misc.buttons.snooper.mixin.UTSnooperClient (mixins.tweaks.misc.buttons.snooper.client.json) [unknown-location]
		mod.acgaming.universaltweaks.tweaks.performance.fps.mixin.UTUncapFPSMixin (mixins.tweaks.performance.fps.json) [unknown-location]
		me.jellysquid.mods.phosphor.mixins.lighting.client.MixinMinecraft (mixins.phosphor.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 663805640 bytes (633 MB) / 1533018112 bytes (1462 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                          | Version                  | Source                                             | Signature                                |
	|:----- |:--------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                   | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LC    | mcp                         | 9.42                     | minecraft.jar                                      | None                                     |
	| LC    | FML                         | 8.0.99.99                | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                       | 14.23.5.2859             | forge-1.12.2-14.23.5.2859.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | creativecoredummy           | 1.0.0                    | minecraft.jar                                      | None                                     |
	| LC    | itemphysic                  | 1.4.0                    | minecraft.jar                                      | None                                     |
	| LC    | ivtoolkit                   | 1.3.3-1.12               | minecraft.jar                                      | None                                     |
	| LC    | xaerominimap_core           | 1.12.2-1.0               | minecraft.jar                                      | None                                     |
	| LC    | mixinbooter                 | 8.6                      | minecraft.jar                                      | None                                     |
	| LC    | configanytime               | 1.0                      | !configanytime-1.0.jar                             | None                                     |
	| LC    | movillages                  | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                         | None                                     |
	| LC    | orbis-lib                   | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build411.jar                | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LE    | aether                      | 0.3.0                    | aether_ii-1.12.2-0.3.0+build411-universal.jar      | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| L     | alcatrazcore                | 1.0.4                    | alcatrazcore-1.0.4.jar                             | None                                     |
	| L     | aquaculture                 | 1.6.8                    | Aquaculture-1.12.2-1.6.8.jar                       | None                                     |
	| L     | carrots                     | 1.0.0b1                  | carrotslib-mc1.12.2-1.0.0b1.jar                    | None                                     |
	| L     | armorunder                  | 1.0.0                    | armorunder-mc1.12.2-1.0.0.jar                      | None                                     |
	| L     | attributefix                | 1.0.12                   | AttributeFix-Forge-1.12.2-1.0.12.jar               | None                                     |
	| L     | autoreglib                  | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| L     | baubles                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| L     | llibrary                    | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                         | None                                     |
	| L     | iceandfire                  | 1.9.1                    | iceandfire-1.9.1-1.12.2.jar                        | None                                     |
	| L     | reachfix                    | 1.0.9                    | ReachFix-1.12.2-1.0.9.jar                          | None                                     |
	| L     | mujmajnkraftsbettersurvival | 1.5.3                    | better_survival-1.5.3.jar                          | None                                     |
	| L     | betterbiomeblend            | 1.12.2-1.1.7-forge       | betterbiomeblend-1.12.2-1.1.7-forge.jar            | None                                     |
	| L     | forgelin                    | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| L     | betterfoliage               | 2.3.2                    | BetterFoliage-MC1.12-2.3.3.jar                     | None                                     |
	| L     | betternether                | 0.1.8.6                  | betternether-0.1.8.6.jar                           | None                                     |
	| L     | biomesoplenty               | 7.0.1.2445               | BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar      | None                                     |
	| L     | bountifulbaubles            | 0.0.1                    | Bountiful Baubles-1.12.2-0.1.8.jar                 | None                                     |
	| L     | chancecubes                 | 1.12.2-5.0.2.385         | ChanceCubes-1.12.2-5.0.2.385.jar                   | None                                     |
	| L     | ctm                         | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| L     | jei                         | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| L     | chisel                      | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| L     | comforts                    | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                        | None                                     |
	| L     | coralreef                   | 2.0                      | CoralReef-2.5-1.12.2.jar                           | None                                     |
	| L     | craftstudioapi              | 1.0.0                    | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar | None                                     |
	| L     | creativecore                | 1.10.0                   | CreativeCore_v1.10.71_mc1.12.2.jar                 | None                                     |
	| L     | doggytalents                | 1.15.1.6                 | DoggyTalents-1.12.2-1.15.1.6.jar                   | None                                     |
	| L     | dldungeonsjbg               | 1.14.12                  | DoomlikeDungeons-1.14.12-MC1.12.2.jar              | None                                     |
	| L     | mocreatures                 | 12.3.1                   | DrZharks-MoCreatures-Extended-12.3.1.jar           | None                                     |
	| L     | sereneseasons               | 1.2.18                   | SereneSeasons-1.12.2-1.2.18-universal.jar          | None                                     |
	| L     | orelib                      | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | None                                     |
	| L     | dsurround                   | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar             | None                                     |
	| L     | reccomplex                  | 1.4.8.5                  | RecurrentComplex-1.4.8.5.jar                       | None                                     |
	| L     | dynamictrees                | 1.12.2-0.9.29            | DynamicTrees-1.12.2-0.9.29.jar                     | None                                     |
	| L     | dynamictreesbop             | 1.12.2-9999.9999.9999z   | DynamicTreesBOP-1.12.2-1.5.2.jar                   | None                                     |
	| L     | twilightforest              | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| L     | dynamictreesttf             | 1.12.2-1.2.3             | dynamictreesTheTwilightForest-1.12.2-1.2.3.jar     | None                                     |
	| L     | eyeofdragons                | 0.0.1                    | eyeofdragons-0.0.2.jar                             | None                                     |
	| L     | foodexpansion               | 1.3                      | FoodExpansion1.3.3-1.12.2.jar                      | None                                     |
	| L     | cfm                         | 6.3.0                    | furniture-6.3.2-1.12.2.jar                         | None                                     |
	| L     | gravestone                  | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
	| L     | harvest                     | 1.12-1.2.8-25            | Harvest-1.12-1.2.8-25.jar                          | None                                     |
	| L     | ichunutil                   | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | None                                     |
	| L     | teslacorelib                | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar                   | None                                     |
	| L     | industrialforegoing         | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| L     | inventorypets               | 2.0.15                   | inventorypets-1.12-2.0.15.jar                      | None                                     |
	| L     | inventorytweaks             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | None                                     |
	| L     | ironchest                   | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| L     | mca                         | 6.1.0                    | MCA-1.12.2-6.1.0-universal.jar                     | None                                     |
	| L     | mcwbridges                  | 1.0.6                    | mcw-bridges-1.0.6b-mc1.12.2.jar                    | None                                     |
	| L     | mcwdoors                    | 1.3                      | mcw-doors-1.0.3-mc1.12.2.jar                       | None                                     |
	| L     | mcwfences                   | 1.0.0                    | mcw-fences-1.0.0-mc1.12.2.jar                      | None                                     |
	| L     | mcwtrpdoors                 | 1.0.2                    | mcw-trapdoors-1.0.3-mc1.12.2.jar                   | None                                     |
	| L     | mcwwindows                  | 1.0                      | mcw-windows-1.0.0-mc1.12.2.jar                     | None                                     |
	| L     | mobends                     | 1.2.1                    | MoBends_1.12.2-1.2.1-19.12.21.jar                  | None                                     |
	| L     | morph                       | 7.2.0                    | Morph-1.12.2-7.2.1.jar                             | None                                     |
	| L     | mousetweaks                 | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
	| L     | naturescompass              | 1.8.5                    | NaturesCompass-1.12.2-1.8.5.jar                    | None                                     |
	| L     | neat                        | 1.4-17                   | Neat 1.4-17.jar                                    | None                                     |
	| L     | patchouli                   | 1.0-23.6                 | Patchouli-1.0-23.6.jar                             | None                                     |
	| L     | ruins                       | 17.2                     | Ruins-1.12.2.jar                                   | None                                     |
	| L     | simpledifficulty            | 0.3.9                    | SimpleDifficulty-1.12.2-0.3.9.jar                  | None                                     |
	| L     | soaringstructures           | 2.5.2 - 1.12.2           | Soaring Structures 2.5.2 - 1.12.2.jar              | None                                     |
	| L     | spartanweaponry             | 1.5.3                    | SpartanWeaponry-1.12.2-1.5.3.jar                   | None                                     |
	| L     | torchmaster                 | 1.8.5.0                  | torchmaster_1.12.2-1.8.5.0.jar                     | None                                     |
	| L     | torchslabmod                | v1.5.2                   | torchslabmod-1.12.2-v1.5.2.jar                     | None                                     |
	| L     | universaltweaks             | 1.12.2-1.8.0             | UniversalTweaks-1.12.2-1.8.0.jar                   | None                                     |
	| L     | wearablebackpacks           | 3.2.6                    | WearableBackpacks-RLCraft-1.12.2-3.2.6.jar         | None                                     |
	| L     | xaerominimap                | 23.8.0                   | Xaeros_Minimap_23.8.0_Forge_1.12.jar               | None                                     |
	| L     | phosphor-lighting           | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50.jar                  | None                                     |
	| L     | rtg                         | 6.1.0.0-snapshot.1       | RTG-1.12.2-6.1.0.0-snapshot.1.jar                  | None                                     |
	| L     | teslacorelib_registries     | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar                   | None                                     |

	Loaded coremods (and transformers): 
TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
  
SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  com.charles445.simpledifficulty.asm.SimpleDifficultyASM
RBLoadingPlugin (RealBench-1.12.2-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.18-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
ForgelinPlugin (Forgelin-1.8.4.jar)
  
ItemPatchingLoader (ItemPhysic_Full_1.4.37_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
XaeroMinimapPlugin (Xaeros_Minimap_23.8.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
  xaero.common.core.transformer.WorldClientTransformer
  xaero.common.core.transformer.EntityPlayerMPTransformer
  xaero.common.core.transformer.EntityPlayerSPTransformer
  xaero.common.core.transformer.PlayerListTransformer
  xaero.common.core.transformer.SaveFormatTransformer
  xaero.common.core.transformer.GuiIngameForgeTransformer
  xaero.common.core.transformer.MinecraftServerTransformer
  xaero.common.core.transformer.GuiBossOverlayTransformer
  xaero.common.core.transformer.ModelRendererTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MixinBooter (!mixinbooter-8.6.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
UniversalTweaksCore (UniversalTweaks-1.12.2-1.8.0.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CreativePatchingLoader (CreativeCore_v1.10.71_mc1.12.2.jar)
  
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
  
ReachFixPlugin (ReachFix-1.12.2-1.0.9.jar)
  meldexun.reachfix.asm.ReachFixClassTransformer
SpartanWeaponry-MixinLoader (SpartanWeaponry-1.12.2-1.5.3.jar)
  
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
ConfigAnytimePlugin (!configanytime-1.0.jar)
  
Better Biome Blend (betterbiomeblend-1.12.2-1.1.7-forge.jar)
  
BetterFoliageLoader (BetterFoliage-MC1.12-2.3.3.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.14761 Compatibility Profile Context 21.30.02.19 30.0.13002.19003' Renderer: 'AMD Radeon(TM) Graphics'

**Comment by ACGaming** [comment]
Is this verifiably caused by Universal Tweaks?

**Comment by FinnagianNightshad** [comment]
it only causes the crash when i put it and its requirements in my game

**Comment by ACGaming** [comment]
Could it be related to Aether II?

**Comment by mczph** [comment]
Don't use `phosphor-1.12.2-0.2.6+build50.jar`,it's out of date.Please use [hesperus](https://www.curseforge.com/minecraft/mc-mods/hesperus) instead.By the way,your java version is too old(.51),consider updating it to a newer one.

**Comment by ACGaming** [comment]
Any news concerning this?
