### ISSUE TITLE
Server refuses to launch on latest forge version of 1.12.2

### ISSUE THREAD

**Issue by Desenrrollado** [ACGaming/UniversalTweaks#3]
I've uploaded both the latest version of my crash reports and latest logs. Though even with everything I've removed I can't seem to launch the server. Which is a bit of let down considering Universal Tweaks seems like a nice mod. I look forward to continued progress of this and Extra Sounds. Thank you for taking the time to make these mods, fix other issues in existing mods and continuing to mod 1.12.2

[latest.log](https://github.com/ACGaming/UniversalTweaks/files/9956791/latest.log)
[crash-2022-11-07_18.23.12-server.txt](https://github.com/ACGaming/UniversalTweaks/files/9956792/crash-2022-11-07_18.23.12-server.txt)

**Comment by ACGaming** [comment]
This was resolved in d05308a3d4a3e229a5bb59eecd0111a19bf4545a
You can always fetch the cutting-edge version by navigating to the [Actions](https://github.com/ACGaming/UniversalTweaks/actions) tab, selecting the most recent workflow run at the top and scrolling down to the Artifacts section where you can download the builds.
You‘d want to put the regular mod file without the `sources` into your game.

**Comment by Desenrrollado** [comment]
Thank you for filling me in. It at least didn't spit the same error out. However now it's

**Comment by ACGaming** [comment]
Yeah, you should definitely remove ExtraSounds and AssetMover from the server as they are only needed/working on client side.
