### ISSUE TITLE
[Suggestion] patch Experience Bug when switching dimensions

### ISSUE THREAD

**Issue by nocturni** [ACGaming/UniversalTweaks#312]
i feel like this would go well in Universal Tweaks
https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug

**Comment by ACGaming** [comment]
Already handled by the „Dimension Change Player States“ bugfix.

**Comment by nocturni** [comment]
i have it toggled but going to the nether still removes my XP

**Comment by ACGaming** [comment]
I may have to implement the same method ‚Fix Experience Bug‘ is using as an additional bandaid.
