### ISSUE TITLE
Mixinbooter Bug

### ISSUE THREAD

**Issue by Devilswarchild** [ACGaming/UniversalTweaks#377]
Universal Tweaks - UniversalTweaks-1.12.2-1.9.0.jar
Mixinbooter - !mixinbooter-8.8.jar
Forge - 14.23.5.2860
mc 1.12.2

So universal tweaks is telling me I need mixinbooter 8.0 or above and that my installation of mixinbooter8.8 is apparently missing.

no idea why this is happening

![image](https://github.com/ACGaming/UniversalTweaks/assets/27385258/f5c17bc9-ec79-4c42-a8fc-d243ccae4eb2)

[latest.log](https://mclo.gs/tNJnA6x)

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/14315705/debug.log)

**Comment by jchung01** [comment]
Try launching without FermiumBooter. It does the same thing as MixinBooter, so it will probably cause unintended behavior. This means you probably need to use CensoredASM for now instead of FermiumASM. If it still doesn't work, try disabling the Essentials mod as that also has issues with MixinBooter.

**Comment by Desenrrollado** [comment]
Can confirm it's this. Many things were changed within Fermium. Making it incompatible with the following so far.

[Vintage Fix](https://modrinth.com/mod/vintagefixl)
[Modern Splash](https://modrinth.com/mod/modern-splash)
[Universal Tweaks](https://modrinth.com/mod/universal-tweaks)
[Config Anytime](https://www.curseforge.com/minecraft/mc-mods/configanytime)

 It's a question of support being added I'd assume.

**Comment by ACGaming** [comment]
As of now, Universal Tweaks is solely built around the infrastructure of MixinBooter, using its designated mixin config functionality as well as features from MixinExtras. Can't provide support for other mixin loaders from within Universal Tweaks.
