### ISSUE TITLE
No warning when using Universal Tweaks with ChunkGenLimiter

### ISSUE THREAD

**Issue by kadirac** [ACGaming/UniversalTweaks#379]
ChunkGenLimiter is a mod that shares Universal Tweaks' chunk generation limiting functionality, with the same configuration options. However, using both doesn't give a warning like using some other redundant mods (i.e. Surge) does.

**Comment by kadirac** [comment]
this happens whether or not i have chunk gen limit toggle set to true fwiw

**Comment by kadirac** [comment]
i'm too tired to test it rn but adding a class check for `io.github.barteks2x.chunkgenlimiter.coremod.ChunkGenLimitTransformer` might work?
this is an educated guess based off the premise that the class it's trying to detect isn't loaded

**Comment by jchung01** [comment]
This should be fixed by 76cadee which will be in the next UT update. You can test with the latest Github Actions build artifact [here](https://github.com/ACGaming/UniversalTweaks/actions/runs/7922664852).
