### ISSUE TITLE
Universal Tweaks isn't good at performance side.

### ISSUE THREAD

**Issue by VulonVahlok** [ACGaming/UniversalTweaks#380]
![2024-02-15_21 54 43](https://github.com/ACGaming/UniversalTweaks/assets/71938170/b5145ed6-da43-4284-bb56-497469522037)
 
Sorry I didn't directly controlled which mods aren't working properly in Universal Tweaks but after removing all these incompatible mods my game dies of performance issues which is fixed after adding these mods back. Considering that Universal Tweaks needs a fix around these mods or shouldn't be a incompatible with mod itself.

**Comment by ACGaming** [comment]
The listed mods are unable to affect performance this much, so this has to be a modpack-specific issue overall. Instead of removing the listed mods, you could also disable the respective tweaks within Universal Tweaks which should avoid the claimed performance issues as well.
