### ISSUE TITLE
Steel feathers can be used for sprinting [Elenai Dodge 2 mod integration]

### ISSUE THREAD

**Issue by Grizdor** [ACGaming/UniversalTweaks#411]
When the Elenai Dodge 2 mod integration for sprinting using feathers is enabled in the config, it's actually possible to sprint using steel feathers (from wearing armor or from the weight potion effect).

Mods :
- Minecraft Forge [14.23.5.2860]
- Universal Tweaks [1.10.0]
- ConfigAnytime [2.0]
- MixinBooter [8.8]
- Elenai Dodge 2 [1.1.0]

**Comment by ACGaming** [comment]
Enhancement further discussed here: https://github.com/ACGaming/UniversalTweaks/discussions/364
