### ISSUE TITLE
Installing with Kemonocraft will result in a recipe error

### ISSUE THREAD

**Issue by 167OSS** [ACGaming/UniversalTweaks#412]
After installing Kemonocraft, you can synthesize some of the food for this mod with any item
![image](https://github.com/ACGaming/UniversalTweaks/assets/78334210/8ca98fbb-94b3-4814-b174-856aa8fecba6)
![image](https://github.com/ACGaming/UniversalTweaks/assets/78334210/86de16f5-a1fd-4557-ba74-67fc3070b06c)

**Comment by ACGaming** [comment]
Please disable the `Crafting Cache` tweak under `Tweaks -> Performance` for now. Since KemonoCraft is closed source and obfuscated with ProGuard, it's pretty hard to add compatibility besides disabling for this matter.
