### ISSUE TITLE
Epic Siege Mod digger AI debugger not removed with config enabled.

### ISSUE THREAD

**Issue by fullskele** [ACGaming/UniversalTweaks#42]
![image](https://user-images.githubusercontent.com/8630389/211221225-04cb130f-b479-459f-a7b7-3d5772b70ba1.png)
![image](https://user-images.githubusercontent.com/8630389/211221330-5ad5e788-0325-49f3-a260-966bad276368.png)

**Comment by ACGaming** [comment]
Can‘t reproduce with a minimal set of mods. Is your Epic Siege Mod at the latest version and did you try deleting your config?
![](https://user-images.githubusercontent.com/4818419/211334191-a22a7952-e52d-465c-91e3-9b1d1f010817.png)
