### ISSUE TITLE
Crash when generating Stronghold

### ISSUE THREAD

**Issue by michelegargiulo** [ACGaming/UniversalTweaks#423]
Safe Stronghold generation is ON in UT config, and I think this can be related.
Upon re-entering the world the crash did not repeat.

Crash report:
https://mclo.gs/QMElFDp

**Comment by ACGaming** [comment]
Might be an incompatibility across multiple mods, been this way for a while now. Feel free to turn that feature off for the time being.

**Comment by ACGaming** [comment]
Fixed with 7326f9be5d1a640f982c23e98786fd55bd0187e5.
