### ISSUE TITLE
 my game crashes instantly when I open the launcher.

### ISSUE THREAD

**Issue by javiburatos** [ACGaming/UniversalTweaks#426]
my game crashes instantly when I open the launcher. Iy don´t give me a crash report but here I post the log.
[latest.log](https://github.com/ACGaming/UniversalTweaks/files/14899290/latest.log)

**Comment by ACGaming** [comment]
Please install the required dependencies [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) and [ConfigAnytime](https://www.curseforge.com/minecraft/mc-mods/configanytime) as well!
