### ISSUE TITLE
Disable End Credits upon entering exit portal.

### ISSUE THREAD

**Issue by Lylythii** [ACGaming/UniversalTweaks#43]
Would be nice if you could disable the End Credits that appear the first time you enter the exit portal.

**Comment by Turkey9002** [comment]
@ACGaming 
I was testing this in a compiled build (up to date without any other mods) and there's this really odd bug whenever this is enabled. When you change the game mode via command, the gui won't update and your inventory does not change but properties like being able to fly does. Rejoining the world properly changes your game mode though

**Comment by ACGaming** [comment]
@Turkey9002 Thanks for the report! Can you test this one again with this build?
https://github.com/ACGaming/UniversalTweaks/actions/runs/4046693692

**Comment by Turkey9002** [comment]
> @Turkey9002 Thanks for the report! Can you test this one again with this build? https://github.com/ACGaming/UniversalTweaks/actions/runs/4046693692

Works perfectly again!
