### ISSUE TITLE
Is it compatible with Modern Warfare Cubed?

### ISSUE THREAD

**Issue by fzrdwa123456** [ACGaming/UniversalTweaks#453]
When I fire my gun, the smoke from the weapon makes the water surface transparent. Could you please tell me what option I should turn off to resolve this issue?
![屏幕截图 2024-05-06 125354](https://github.com/ACGaming/UniversalTweaks/assets/130232431/b5757125-fc96-44eb-81b8-b81317690489)

**Comment by ACGaming** [comment]
That would be the `Depth Mask` bugfix under `Bugfixes -> Misc`. Fixes vanilla issues but causes other issues with mods which already built around the flawed vanilla behavior.

**Comment by fzrdwa123456** [comment]
> That would be the `Depth Mask` bugfix under `Bugfixes -> Misc`. Fixes vanilla issues but causes other issues with mods which already built around the flawed vanilla behavior.

Thank you, everything is fine now
