### ISSUE TITLE
Dedicated server, RandomThings: Player stall in void when teleporting to Spectre dimension

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#460]
When player in `Survival mode` using Spectre Key from mod RandomThings he teleported to Spectre dimension.
Through, when im using my [tweaked configs of UT](https://github.com/Krutoy242/Enigmatica2Expert-Extended/blob/master/config/Universal%20Tweaks%20-%20Tweaks.cfg), player is stall in void dimension forever. Resetting configs to defaults (removing `Universal Tweaks - Tweaks.cfg`) fixes issue.

There is normal behavior with resetted configs:

https://github.com/ACGaming/UniversalTweaks/assets/936618/4b47fc68-5b92-4bde-8351-6d60a27465cf

And there is behavior of with my custom configs:

https://github.com/ACGaming/UniversalTweaks/assets/936618/73719631-5dfe-4eef-9168-3ff0681f620b

Note that issue is instantly fixed if player game mode changed to creative:

https://github.com/ACGaming/UniversalTweaks/assets/936618/d5964f8b-e209-42cc-a68b-95b0b13aeec9

There is changes i made for better visualize:

[~bugged-to-default-unbugged.patch](https://github.com/ACGaming/UniversalTweaks/files/15264005/bugged-to-default-unbugged.patch)

Notes:

- Defaulting only `Max speed` values does not helping to fix issue
- No server stall detected (TPS is normal, server responsive)
- We already had similar issue that was fixed https://github.com/Krutoy242/Enigmatica2Expert-Extended/commit/b3e539b1f3f99d64e39435aeaeb111bad532fb90
- Clientside configs changes doesn't matter

[server debug.log](https://github.com/ACGaming/UniversalTweaks/files/15264053/debug.log)

**Comment by ACGaming** [comment]
Would require binary-searching to determine the exact config setting. When that's supplied, I can come up with a solution.
