### ISSUE TITLE
[Enhancement] Better Placement incompat with many mods

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#473]
In E2E-E there is many mods that add blocks required holding right klick. Almost all of them can't be used as intended when `Better Placement` option is turned on, unless `Force New Location` turned on too (but i dont want to turn it on).

Most annoying with sieves since its crucial to hold right-click on using them - saves lot of time. E2E-E players even [reporting it as a bug](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/370).

https://github.com/ACGaming/UniversalTweaks/assets/936618/477c3f03-0535-4394-91a5-8bf0b30a81eb

This issue already reported [here](https://github.com/ACGaming/UniversalTweaks/issues/416#issuecomment-2047325481), but since it was ignored I assume you just missed it accidentally.

The [fix](https://github.com/ACGaming/UniversalTweaks/commit/b9c5193ca1fa08b15435c4a417f764093f5ea587) for Storage Drawers works fine btw.
I would like if there would be some kind of *universal* fix, like checking if right-click event was cancelled. Or at least blacklist of blocks that should not cancel placement.

**Comment by jchung01** [comment]
Added a fix that should be pretty much universal. Tested holding right-click with trapdoors, doors, and the mentioned sieve. Only oddity is that interactable blocks (sieves, machines, doors, etc.) ignore `Force New Location=true`, but that shouldn't be too much of an issue. Placement of non-interactable blocks is still limited by `Force New Location` as usual though.

**Comment by Krutoy242** [comment]
@ACGaming When you planning to release UT version with this fix?

**Comment by Krutoy242** [comment]
Still waiting for the release with this change!
# 😏
