### ISSUE TITLE
Latest Version 1.11.0 Crashes With RailCraft Installed

### ISSUE THREAD

**Issue by RConTRS** [ACGaming/UniversalTweaks#478]
Version 1.11.0 Crashes At Phase 3/7 If RailCraft Is Installed, However Version 1.10.0 Seems To Have No Issues.

Crash Report : [crash-2024-05-29_18.06.28-client.txt](https://github.com/ACGaming/UniversalTweaks/files/15486404/crash-2024-05-29_18.06.28-client.txt)

**Comment by ACGaming** [comment]
Fixed in 1e3cb990eb5012bc8b27304aecfa56ab25af20ba, disable `Mods -> Railcraft -> No Beta Warning` for now when not using the Beta versions.
