### ISSUE TITLE
Rare "stuck" game launch due to Incurable Potions tweak

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#480]
Happens in a modpack environment in about 2-3% of launches, not sure why. Figured it's best to have it documented.
https://mclo.gs/4s8ZtYG

**Comment by jchung01** [comment]
Seems to happen in E2E:E as well https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/355
Possibly some other mod transforming a related class using ASM and causing the crash. Particular mod/reason is unknown though.

**Comment by xJon** [comment]
After disabling Incurable Potions, it seemingly occurred again due to the Potion Amplifier fix: https://mclo.gs/q5dqX0f
But after disabling that too, it happened again with *a bunch* of Universal Tweaks features mentioned, as well as Thaumic Augmentation: https://mclo.gs/hs6dGl9#L382
Something weird is going on.

**Comment by ACGaming** [comment]
Thaumic Augmentation is utilizing a bunch of direct ASM transformations which don't stack with both other ASM code modifications and mixins. Virtually endless possibilities of incompatibilities!

**Comment by xJon** [comment]
@ACGaming Thing is, this does not occur consistently on launch but only sometimes. Might be some weird race condition.

**Comment by jchung01** [comment]
Maybe try running with the java arg `-Dmixin.dumpTargetOnFailure=true`? When it crashes, this will dump the erroring class file to the folder ./.mixin.out, which you can upload here and maybe it might provide some insight.

**Comment by xJon** [comment]
From some extensive testing, I believe this is caused by LoliASM's `optimizeFMLRemapper` feature - I can't reproduce the issues with `B:optimizeFMLRemapper=false`.
