### ISSUE TITLE
Error when joining server with UT

### ISSUE THREAD

**Issue by CalaMariGold** [ACGaming/UniversalTweaks#49]
Hi, one of my players playing my modpack Trepidation is getting an error when joining a server, and it seems to be that UT is the cause, specifically "Max Health Fix" which is enabled.

Log: https://mclo.gs/azZyJCl

The original issue is located here: https://github.com/CalaMariGold/TREPIDATION/issues/6

Let me know if you need any other information, thanks!

**Comment by ACGaming** [comment]
The player has an invalid cached health value with a wrong decimal separator. Forced locale for a proper decimal point in d9a3a89c5e4e376407484d282b63f61f868eb8ec and added an additional safety check for existing values in 09ea1f54bd81954440db861da1519c6bb34a7675.

**Comment by ACGaming** [comment]
Until updating, you can only disable the tweak for the time being.
