### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kasia1403** [ACGaming/UniversalTweaks#5]
Is this crash from Your mod 

https://paste.ee/p/rAsOo?

**Comment by ACGaming** [comment]
You‘d have to remove Surge in order to use Universal Tweaks. Check the incompatible mods here: https://www.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4095116

**Comment by Kasia1403** [comment]
Is also Aether II mod incompatible ? Because my latest.log says something about Aether II mod.

**Comment by ACGaming** [comment]
Aether II appears to work fine with Universal Tweaks, so it‘s most likely because of the clash with Surge.

**Comment by ACGaming** [comment]
The functionality of Surge is included, you can just remove it as it‘s redundant.
