### ISSUE TITLE
game flashing when custommainmenu switch background

### ISSUE THREAD

**Issue by xx146542xx** [ACGaming/UniversalTweaks#510]
using mod form [latest action ](https://github.com/ACGaming/UniversalTweaks/actions/runs/9813127398)and other mods
["UniversalTweaks-1.12.2-1.11.0.jar" 
"!configanytime-3.0.jar" 
"!mixinbooter-9.1.jar"*not related just forgot to delete 
"CustomMainMenu-MC1.12.2-2.0.9.1.jar" 
"FpsReducer-mc1.12.2-1.20.jar" 
"ResourceLoader-MC1.12.1-1.5.3.jar"] 
are latest version 
using [nomiceu1.7a4](https://github.com/Nomi-CEu/Nomi-CEu/releases/tag/1.7-alpha-4) resources 

https://github.com/ACGaming/UniversalTweaks/assets/109429390/d8c1379b-d5f8-48b1-a617-b65d59892bec

**Comment by ACGaming** [comment]
And you're confident that the issue is solely caused by Universal Tweaks? If so, please try to determine the related config setting.

**Comment by xx146542xx** [comment]
it happened when mainmenu fps limited by fpsreducer or other mods/manually set below 20fps
caused by

>          # Removes the hardcoded 30 FPS limit in screens like the main menu
>         B:"Uncap FPS"=true
 all loaded mods:
![image](https://github.com/ACGaming/UniversalTweaks/assets/109429390/2741b51f-287c-4ced-8c00-362bdeb31bd0)

**Comment by ACGaming** [comment]
Well, when other mods are affecting the FPS of the main menu, you simply have to disable the tweak as they are essentially modifying the same thing.
