### ISSUE TITLE
No back key

### ISSUE THREAD

**Issue by al-wei** [ACGaming/UniversalTweaks#516]
![QQ_1720989491255](https://github.com/user-attachments/assets/6fbf3a0c-f0f3-48c2-a359-0c1d89af2f69)
![QQ_1720989532756](https://github.com/user-attachments/assets/b6bc295b-522e-4442-bbdf-2f7454ff41db)

**Comment by ACGaming** [comment]
@WaitingIdly

**Comment by WaitingIdly** [comment]
definitely incorrect behavior. in the mean time, you can disable this behavior via `[07] Hide Invalid Arrow Buttons`. this is accessed in the config via config -> Tweaks -> Advancements

**Comment by WaitingIdly** [comment]
circling back to this - i do not have this issue in the dev environment. checking through possible reasons, it the mixin `utHideInvalidButtons` fails that could reproduce what you are seeing. however, no `latest.log` or relevant files have been provided to diagnose that issue.
if you can reproduce this, please provide the reproduction steps and please include a log file where this incident happens.

![image](https://github.com/user-attachments/assets/92290fd4-a62b-4337-9f6b-1a331fe218d9)
![image](https://github.com/user-attachments/assets/fe64b0cb-4d7c-4051-a74f-78c9de3ae702)

**Comment by al-wei** [comment]
https://mclo.gs/BDP0DGj

**Comment by WaitingIdly** [comment]
i am unable to identify what the issue may be caused by from your log. could you reduce your mod count as much as possible to provide a minimum reproduction?
to create an arbitrary number of advancement tabs, i use triumph + a copy/pasted script a few dozen times.

**Comment by al-wei** [comment]
> i am unable to identify what the issue may be caused by from your log. could you reduce your mod count as much as possible to provide a minimum reproduction? to create an arbitrary number of advancement tabs, i use triumph + a copy/pasted script a few dozen times.

I don't have that much time to spend on a problem that can be solved.
This is a modpack close to 400mod.
My rule is the game doesn't crash, so keep playing.

**Comment by al-wei** [comment]
This is modpack.
https://www.curseforge.com/minecraft/modpacks/al-nl/files/5757705

**Comment by WaitingIdly** [comment]
i am not willing to download and pour through an entire modpack. the modpack author should change the default config option, as some mod within the modpack is incompatible. if the incompatibility is identified, or at least narrowed down, ill fix it.
