### ISSUE TITLE
Mixin injection failed in version 1.12.0, causing the game to become unresponsive

### ISSUE THREAD

**Issue by liuhongyou12345** [ACGaming/UniversalTweaks#536]
Certainly! Here's an English feedback report for the issue you're experiencing with the Universal Tweaks mod:

Subject: Mixin Application Failure for UT3DAnaglyphMixin in UniversalTweaks

Dear UniversalTweaks Development Team,

I hope this message finds you well. I'm reaching out because I've encountered an issue while using the latest version of UniversalTweaks (1.12.2-1.12.0) in my Minecraft installation. Specifically, the Mixin application for UT3DAnaglyphMixin has failed, causing issues during the game initialization process.

Details of the Issue
During the game startup, the following exception was thrown:

Java
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field field_146502_i was not located in the target class net.minecraft.client.gui.GuiVideoSettings. Using refmap universaltweaks.refmap.json
The stack trace indicates that the Mixin UT3DAnaglyphMixin from the mod UniversalTweaks-1.12.2-1.12.0.jar failed to apply due to a missing field field_146502_i in the target class net.minecraft.client.gui.GuiVideoSettings.

Steps to Reproduce
Install the latest version of UniversalTweaks (1.12.2-1.12.0).
Launch Minecraft with the following configuration:
Minecraft version: 1.12.2
Forge version: 14.23.5.2860
Other mods installed: (List any other relevant mods here)
Observe the log output during startup. The failure should be visible in the log files.
Expected Behavior
The Mixin should apply correctly without any errors, allowing the game to start and run smoothly.

Actual Behavior
The Mixin application fails, resulting in the game crashing or not starting properly.

Environment
Minecraft version: 1.12.2
Forge version: 14.23.5.2860
UniversalTweaks version: 1.12.2-1.12.0
Operating system: Windows
Java version: 1.8.0_382
Additional Information
The log file and JStack dump have been attached for reference. (You can include links to these files if you are sending this via email or another platform.)
I am running the game on a machine with the following specifications: (Include CPU, RAM, GPU, etc.)
Request
Could you please provide some guidance or a fix for this issue? I would appreciate any insights or updates regarding the compatibility of UT3DAnaglyphMixin with the current version of Minecraft and Forge. If there are any steps I can take to resolve this on my end, please let me know as well.

Thank you very much for your time and assistance. I look forward to hearing from you soon.

Please feel free to adjust the details and personalize the message as needed. If you need further assistance or have additional information to include, let me know!
[minecraft-exported-jstack-dump-2024-08-14T10-14-44.txt](https://github.com/user-attachments/files/16607105/minecraft-exported-jstack-dump-2024-08-14T10-14-44.txt)
[minecraft-exported-logs-2024-08-14T10-14-39.txt](https://github.com/user-attachments/files/16607106/minecraft-exported-logs-2024-08-14T10-14-39.txt)

**Comment by ACGaming** [comment]
Gotta love AI reports! Looks like another mod is already modifying the button/field.
