### ISSUE TITLE
Says it requires MixinBooter 8.9 or above on launch when it's already installed

### ISSUE THREAD

**Issue by IdkWhatNameThingyToPut** [ACGaming/UniversalTweaks#542]
Is this mod incompatible with VanillaFix? Everything seems to work fine when either this mod and the one it comes with or VanillaFix is disabled. I think it might be caused by the like load order or renaming of the VanillaFix mod because apparently that's one of the only fixes for it that I've seen and it's worked well till now.

[latest.log](https://github.com/user-attachments/files/16736851/latest.log)

**Comment by ACGaming** [comment]
VanillaFix is considered outdated by today's standards, use [CensoredASM](https://www.curseforge.com/minecraft/mc-mods/lolasm) for improved functionality.
