### ISSUE TITLE
Duplication

### ISSUE THREAD

**Issue by NordicGamerFE** [ACGaming/UniversalTweaks#559]
https://github.com/NordicGamerFE/Ocean-Outlast/issues/155 this is caused by the infusion stone having its durability is a meta and some weird interaction with simple storage

**Comment by ACGaming** [comment]
Is this an interaction issue with Universal Tweaks or a suggestion for a mod tweak?

**Comment by NordicGamerFE** [comment]
its a suggestion for a mod tweak.

**Comment by ACGaming** [comment]
Alright, further progress via https://github.com/ACGaming/UniversalTweaks/discussions/506
