### ISSUE TITLE
[Mod fix] Charm spectres ticking

### ISSUE THREAD

**Issue by Foreck1** [ACGaming/UniversalTweaks#56]
This mod doesn't have anything to do with it, but since it incorporates a version of Save My Stronghold, I wanted to ask.
Charm adds a mob called spectre. Along with the mod, a feature called spectre haunting which checks for a specific structure is added which is currently causing a player tick crash when trying to check for the structure (Stronghold).

[crash report](https://github.com/ACGaming/UniversalTweaks/files/10500544/crash-2023-01-25_11.46.20-server.txt)

[latest log](https://github.com/ACGaming/UniversalTweaks/files/10500553/latest.log)

This happens in an in-dev version of the modpack Rebirth of the Night

Would a fix be within the scope of this mod?

**Comment by ACGaming** [comment]
Can you tell me what is necessary to reproduce this issue? I wandered around a safe strongholds with a lot of spectres around just fine. 🤔
Since the safe stronghold extends from the regular one, it should be working similarly enough.

**Comment by Foreck1** [comment]
This issue happens when playing an indev version of Rebirth of the Night, so it would be rather difficult to emulate the same environment.

**Comment by Foreck1** [comment]
As discussed via DMs, the cause of the problem is obscure and difficult to determine due to the sheer amount of possible culprits. The only "fix" for this issue was to disable the haunting feature in the Charm configuration file.
