### ISSUE TITLE
[Feature Request] Fix Dimension Travel Desync

### ISSUE THREAD

**Issue by RConTRS** [ACGaming/UniversalTweaks#562]
a known issue that occur sometimes on dimension travel, XP/Level Reset Until Picking Up At Least 1 Orb To Bring It Back To Normal, i was a bit surprised this mod doesn't fix it already

**Comment by ACGaming** [comment]
Please verify if this is fixed in your case by the `Dimension Change Player States` bugfix under `Bugfixes -> Entities`.

**Comment by RConTRS** [comment]
![image](https://github.com/user-attachments/assets/41cb4241-a479-4df6-a36a-79d945dc00e0)

it's enabled but for somereason it doesn't work, at least for XP/level
