### ISSUE TITLE
Erebus wand of animation

### ISSUE THREAD

**Issue by NordicGamerFE** [ACGaming/UniversalTweaks#571]
The wand of animation is unreliable nearly non-functional with universal tweaks installed.

**Comment by ACGaming** [comment]
Could you pinpoint the responsible setting yet?

**Comment by NordicGamerFE** [comment]
Found it B:"[1] Swing Through Grass Toggle"=true

**Comment by ACGaming** [comment]
Thanks for the insight, trying to fix this in the next update.
