### ISSUE TITLE
Invalid Mixin Exception Error on server. 

### ISSUE THREAD

**Issue by whatsapp2** [ACGaming/UniversalTweaks#595]
My friends and I made a kitchen sink modpack and added universal tweaks to it. 
Our consoles keep getting spammed with this error.

https://gist.github.com/whatsapp2/268062641777cebff91bd85faeb10715

If anything else is required to submit the report let me know

**Comment by ACGaming** [comment]
Is it really caused by Universal Tweaks?

From the log, it's Had Enough Items complaining about Minecraft Transport Simulator's JEI interface.

**Comment by whatsapp2** [comment]
I am actually not too sure, it mentioned Universal Tweaks to I figured I would post here... Either way I have to relay this to MTS devs, see what they can find and I'll report back

**Comment by whatsapp2** [comment]
I mentioned this issue to MTS dev, hasn't answered at the time of writting this message, but when I was checking my latest.log to see if I got any other error I found this

`Mixin apply for mod universaltweaks failed mixins.tweaks.misc.buttons.anaglyph.json:UT3DAnaglyphMixin from owner universaltweaks -> net.minecraft.client.gui.GuiVideoSettings`

Here's the full log
https://gist.github.com/whatsapp2/ca8cd2f5000cda511a9146cfbc19b45b

**Comment by ACGaming** [comment]
That's just the 3D Anaglyph button tweak failing silently because OptiFine is installed, nothing to worry about.

**Comment by DonBruce64** [comment]
This is indeed a bug with IV.  Y'all can close it out and I'll handle it on my end..
