### ISSUE TITLE
Audio Reload Problem

### ISSUE THREAD

**Issue by ISurrealI** [ACGaming/UniversalTweaks#6]
Looks like a mixins encountered a problem while attaching loadSounds method.
(Line 1703)
https://paste.ee/p/rAsOo

**Comment by ACGaming** [comment]
You‘d have to remove Surge in order to use Universal Tweaks. Check the incompatible mods here: https://www.curseforge.com/minecraft/mc-mods/universal-tweaks/files/4095116
