### ISSUE TITLE
Recipe Book Removal Tweak doesn't completely disable the recipe book

### ISSUE THREAD

**Issue by Turkey9002** [ACGaming/UniversalTweaks#61]
Even with the recipe book disabled through Universal Tweaks, there are still toasts that show up notifying you that you unlocked a new recipe. Fast Workbench completely disables the system entirely.

**Comment by xJon** [comment]
Aren't toasts affected by [Toast Control](https://www.curseforge.com/minecraft/mc-mods/toast-control)?

**Comment by ACGaming** [comment]
They are as well but Fast Workbench actually does the effort of replacing the recipe book with a dummy one, omitting the toasts in the process.

**Comment by xJon** [comment]
@ACGaming In which case perhaps UT could also replace Toast Control rather then do what you're mentioning

**Comment by ACGaming** [comment]
Planned!

**Comment by Turkey9002** [comment]
If you do add Toast Control, I think having the recipe toasts be automatically disabled when the recipe book is turned off should be a feature (since toast control allows you to choose which toasts you want to disable) because it wouldn't make sense to have them enabled without a recipe book.
