### ISSUE TITLE
[Bug] Classic end portal parallax turns white during certain conditions

### ISSUE THREAD

**Issue by Turkey9002** [ACGaming/UniversalTweaks#64]
There's currently an issue with how the classic end portal parallax tweak works. It'll end up turning white or glitchy and you can do this by spawning an Eldritch Guardian from Thaumcraft nearby or flying upwards and looking down at the portal to see it slowly change to white (this can occur much more easily when having a low render distance). This does not occur with the vanilla parallax and I've tested this without any other mods.

**Comment by ACGaming** [comment]
Any screenshots for this?

**Comment by ACGaming** [comment]
It seems like it‘s how the portal reacts to fog. I‘ll see if I can find a way around it.

**Comment by Turkey9002** [comment]
> Any screenshots for this?
![2023-02-03_13 28 16](https://user-images.githubusercontent.com/86805568/216690867-2891a2bf-92ae-4d5f-9eed-a9538e654a78.png)

Looks to be the fog like you said.

**Comment by ACGaming** [comment]
Did some digging and it‘s actually part of another long-lasting rendering issue: https://bugs.mojang.com/browse/MC-3607
Hooray! I guess.

**Comment by xJon** [comment]
True nostalgia backports bugs 😎
