### ISSUE TITLE
Please fix the Model of Doors in 1.12.2

### ISSUE THREAD

**Issue by Titoo8899** [ACGaming/UniversalTweaks#69]
Hi,
cool new Update. I hope you can the doors models of the 1.12.2 fix in the next time.
I love the 1.12.2 but the Doors looks so sad.

**Comment by ACGaming** [comment]
Doesn‘t require a mod, resource packs are already able to do so. You‘d be best off with something like this: https://www.curseforge.com/minecraft/texture-packs/fancy-doors
