### ISSUE TITLE
Doors Bug with the Textures then we look inside the holes

### ISSUE THREAD

**Issue by TitooTVGeilo** [ACGaming/UniversalTweaks#7]
Hi,
a little thinks of doors have holes who  we can look to the other side. But in the last newer versions have minecraft the texture fix what in 1.12.2 and little time between was give. I hope you can this fix. The flat texture was a so long bug in minecraft I hope you can fix it.

Picture:

![2022-11-23_22 41 40](https://user-images.githubusercontent.com/108121897/203650819-7497a095-7f5a-49ec-a709-c90586a5c830.png)

**Comment by ACGaming** [comment]
Charming suggestion, isn‘t the perfect fit for a mod though as resource packs are already able to do so and change textures in the process as well. You‘d be best off with something like this: https://www.curseforge.com/minecraft/texture-packs/fancy-doors
