### ISSUE TITLE
Serious lag about AttributeFix

### ISSUE THREAD

**Issue by mczph** [ACGaming/UniversalTweaks#72]
This problem also appears in the original mod AttributeFix.
When attacking with weapons with high attack power (e.g. 1,000,000) the damage particles causes severe lags.In vanilla enviornment it's unnecessary since the max damage is limitted,but with AttributeFix it's a problem.I think remove the damage particles in code may fix the problem.
Also give an option to limit the max damage.

**Comment by ACGaming** [comment]
As nobody actually needs that high attribute values, configurability should be enough without touching particles.
