### ISSUE TITLE
ClassCastException on game startup

### ISSUE THREAD

**Issue by brisingraerowing** [ACGaming/UniversalTweaks#73]
[Crash Log](https://gist.github.com/brisingraerowing/b1d6258f4a2d4394348ed0ac605518bc)

The game ran fine before installing Immersive Engineering and several addons (and a couple other mods). I'll see if I can find the incompatibility.

**Comment by brisingraerowing** [comment]
The conflict is with [Alternating Flux](https://www.curseforge.com/minecraft/mc-mods/alternating-flux) for whatever bizarre reason.

**Comment by ACGaming** [comment]
It seems to be an internal Universal Tweaks issue with the recently changed attributes tweak. It crashes after a first successful launch, investigating...

**Comment by brisingraerowing** [comment]
That explains things.

**Comment by ACGaming** [comment]
Fixed in 783cd22c6fe066542c815ad80bda92e66f4a7d28.
