### ISSUE TITLE
Pre-init error on UniversalTweaks with GTCEu

### ISSUE THREAD

**Issue by ChromaPIE** [ACGaming/UniversalTweaks#8]
Crash report: https://hastebin.com/ilenametiv.rb

**Comment by ChromaPIE** [comment]
Nevermind. I tried bringing back AI Improvement and Fast Leave Decay but forgot to delete UT, that led to the game successfully showed the warning screen which told me to remove Surge, AII, FLD and Let Me Despawn from the mods, therefore coincidentally fixed the problem.

**Comment by ACGaming** [comment]
Thanks anyways for the report, I‘ll add GregTech to the list of mods that don‘t work well with the obsolete mods screen.
