### ISSUE TITLE
[Suggestion] Collision Damage

### ISSUE THREAD

**Issue by Lylythii** [ACGaming/UniversalTweaks#9]
Configurable collision damage on collision with surfaces akin to elytra.

Renders this (somewhat broken) mod null.
- https://www.curseforge.com/minecraft/mc-mods/collision-damage

**Comment by ACGaming** [comment]
Added to the list, although most likely a little more complicated, comparatively.

**Comment by ACGaming** [comment]
Nevermind, the approach is as simple as it can get, no packet shenanigans.
Works with Wall-Jump, the damage factor needs to be set quite a bit higher than for vanilla though.
