### ISSUE TITLE
[Server Crash] Encountered a ticking entity, skeleton trying to become a player?

### ISSUE THREAD

**Issue by EmyLightsaber** [ACGaming/UniversalTweaks#90]
[crash-2023-02-27_18.03.02-server.txt](https://github.com/ACGaming/UniversalTweaks/files/10846639/crash-2023-02-27_18.03.02-server.txt)

Not really sure what to put here, but I was exploring a cave, and the server crashes every time try to log back in after booting the server up.

**Comment by ACGaming** [comment]
This seems to be related to Untouched Nature. Does the crash occur without it as well?

**Comment by EmyLightsaber** [comment]
I haven't tested without it quite yet. I did however, test without Universal Tweaks, and it still happened. I will follow up with the Untouched Nature dev.

**Comment by ACGaming** [comment]
That‘s also a way to rule it out, closing it for this side then! 🤝

**Comment by Lonelyxiya** [comment]
![image](https://user-images.githubusercontent.com/83713575/222042609-9189ea10-ad70-4806-964e-63f14e9bd8f3.png)
A png for reference
