### ISSUE TITLE
Large lag spikes when used alongside Fluidlogged API?

### ISSUE THREAD

**Issue by Turkey9002** [ACGaming/UniversalTweaks#92]
For awhile I've been having lag spike issues when using that mod with a mod that adds underwater plants (like Subaquatic) and I suspected it to be from Thaumcraft at first but then realized most of the lag came from one of the tweaks in this mod. I updated to the latest version and it seems to not be as bad during testing? I wonder if any changes lately helped with that, I'll still need to check which tweak it could be to fully figure it out

Spark Profilers:
[Subaquatic + Thaumcraft](https://spark.lucko.me/tZAoXiQtUm)
[Subaquatic + Thaumcraft + Universal Tweaks](https://spark.lucko.me/FpaKBmYq0B)
[Same as above but with latest Universal Tweaks version](https://spark.lucko.me/lpem1GgrJY)

**Comment by ACGaming** [comment]
I‘d be thankful if you could determine the tweak involved!

**Comment by Turkey9002** [comment]
@ACGaming 
Earlier I was thinking Frustum Culling would be lowering FPS a bit but I don't think affects that. After a lot more testing though, looks like the latest Fluidlogged API version (v2.0.0) fixed the extra lag that I had when using it with this mod so I'll close the issue but if I do experience anything strange again I'll definitely reopen it.

**Comment by ACGaming** [comment]
Sounds good, thanks for the update!
