### ISSUE TITLE
item entities 05 It's useless

### ISSUE THREAD

**Issue by ztblat** [ACGaming/UniversalTweaks#99]
item entities 05 It's useless，Whether it is minecraft:bucket or <minecraft:bucket>。
and
Can you add Loot Beams？

**Comment by ACGaming** [comment]
It‘s not useless, it‘s intended for gameplay with `Automatic Pickup` disabled.
Loot Beams was added to the [Requested Features](https://github.com/ACGaming/UniversalTweaks/wiki/Requested-Features).
